import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import ParticipantKeyAlertDialog from "@/components/dashboard/participantKey"

import { SiteHeader } from "@/components/site-header";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="max-h-screen">
            <div>
                <SiteHeader></SiteHeader>
            </div>
            <div className="">
                <ParticipantKeyAlertDialog />
                {children}
            </div>
        </div>
    );
}
