import type { Metadata } from "next";
import { Separator } from "@/components/ui/separator";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="py-4 flex flex-row items-center gap-5 px-6 md:px-10">
                    <h2 className="h-min text-center font-bold leading-tight tracking-tighter text-2xl md:text-3xl">NextIsAJug</h2>
                    <div className="hidden md:block ">

                    </div>
                </div>
                <Separator></Separator>
                {children}
            </body>
        </html>
    );
}
